### ISSUE TITLE
Shift-left (`<<`) is broken

### ISSUE THREAD

**Issue by Timwi** [keiwando/biginteger#1]
Not sure if this project is still in active development, but there appears to be an issue:

**STEPS TO REPRODUCE**

`(BigInteger) (-1) << 1`

**EXPECTED RESULT**

`-2`

**ACTUAL RESULT**

`680564733841876926926749214863536422910`

**Comment by keiwando** [comment]
Thanks for pointing that out! The problem should be fixed now. If I accidentally broke something else in the process, please let me know!
